// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_cards_id_ from "./routes/api/cards/[id].ts";
import * as $api_decks_id_ from "./routes/api/decks/[id].ts";
import * as $index from "./routes/index.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $Button from "./islands/Button.tsx";
import * as $deck_view from "./islands/deck-view.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/cards/[id].ts": $api_cards_id_,
    "./routes/api/decks/[id].ts": $api_decks_id_,
    "./routes/index.tsx": $index,
    "./routes/settings.tsx": $settings,
  },
  islands: {
    "./islands/Button.tsx": $Button,
    "./islands/deck-view.tsx": $deck_view,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
